version: '{build}'  
#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /\(doc\).*/
pull_requests:  
  do_not_increment_build_number: true
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/manojkulkarni30/api/v2/package
  api_key:
    secure: /kkvZoE04QHo7umHPGp6NTCbp8tNuuc/SSpaxlGU0QI+l9hibm3ONK3v3MvFVcqC
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: wOB2AdXDbuwFYNzEp9tulWBF8f4CZY54pzAdUEdlaPBMQ6NBdWhY5FOorPE6RjGG
  on:
    branch: master
    appveyor_repo_tag: true